# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0002_auto_20161006_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='comodidad',
            field=models.CharField(choices=[(5, 'muy bueno'), (4, 'bueno'), (3, 'regular'), (2, 'malo'), (1, 'Ns/Nc')], default=1, max_length=1, verbose_name='Comodidad con la que viaja'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='estado_unidad',
            field=models.CharField(choices=[(5, 'muy bueno'), (4, 'bueno'), (3, 'regular'), (2, 'malo'), (1, 'Ns/Nc')], default=1, max_length=1, verbose_name='Estado general de la unidad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='higiene_unidad',
            field=models.CharField(choices=[(5, 'muy bueno'), (4, 'bueno'), (3, 'regular'), (2, 'malo'), (1, 'Ns/Nc')], default=1, max_length=1, verbose_name='Higiene de la unidad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='trato_choferes',
            field=models.CharField(choices=[(5, 'muy bueno'), (4, 'bueno'), (3, 'regular'), (2, 'malo'), (1, 'Ns/Nc')], default=1, max_length=1, verbose_name='Higiene d'),
        ),
    ]
