# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 23:00
from __future__ import unicode_literals

import appencuesta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0003_auto_20161006_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='comodidad',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Comodidad con la que viaja'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='encuestador',
            field=models.ForeignKey(on_delete=appencuesta.models.Encuestador, to='appencuesta.Encuestador'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado_unidad',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Estado general de la unidad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='higiene_unidad',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Higiene de la unidad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='trato_choferes',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Higiene d'),
        ),
    ]
