# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 00:43
from __future__ import unicode_literals

import appencuesta.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0004_auto_20161006_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='momento',
            field=models.CharField(blank='true', choices=[('AA', 'antes de ascender'), ('LD', 'luego de descender')], max_length=2, verbose_name='Momento de la encuesta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='parada_encuesta',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='appencuesta.Parada'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='encuestador',
            field=models.ForeignKey(null='true', on_delete=appencuesta.models.Encuestador, to='appencuesta.Encuestador'),
        ),
    ]
