# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0005_auto_20161006_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='rango_edad',
            field=models.CharField(blank='true', choices=[('JO', 'Jóven (18-25 años)'), ('A1', 'Adulto (25-40 años)'), ('A2', 'Adulto II (40-60 años)'), ('AM', 'Adulto mayor (más de 60 años)')], max_length=2, verbose_name='Rango de edad'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='sexo',
            field=models.CharField(blank='true', choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
