# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0006_auto_20161006_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='nombre de la línea')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank='true', choices=[('Z', 'Zona'), ('H', 'Hito'), ('P', 'Parada')], max_length=1, verbose_name='Tipo de lugar')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del motivo')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='origen_parada',
            field=models.CharField(blank='true', max_length=10, verbose_name='Parada de destino (opcional)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='otro_medio',
            field=models.CharField(blank='true', choices=[('NO', 'No'), ('OLINEA', 'Otra línea'), ('AUTO', 'Automóvil'), ('TAXREM', 'Taxi o Remis'), ('OTRO', 'Otro medio')], max_length=6, verbose_name='Para completar el viaje usa otro medio de transporte?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='veces_dia',
            field=models.CharField(blank='true', choices=[('2OMAS', 'Dos o más'), ('MENOS2', 'Menos de dos')], max_length=6, verbose_name='Veces por día en que realiza este viaje'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='veces_semana',
            field=models.CharField(blank='true', choices=[('TODOS', 'Todos los días'), ('3OMAS', 'Tres o más'), ('MENOS3', 'Menos de tres')], max_length=6, verbose_name='Veces por semana en que realiza este viaje'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='destino_lugar',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_destino_lugar', to='appencuesta.Lugar'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='destino_motivo',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_destino_motivo', to='appencuesta.Motivo'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='linea',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='appencuesta.Linea'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='origen_lugar',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_origen_lugar', to='appencuesta.Lugar'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='origen_motivo',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_origen_motivo', to='appencuesta.Motivo'),
        ),
    ]
