# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0007_auto_20161009_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='conduccion_choferes',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el desempeño de los choferes en la conducción?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='info_choferes',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el nivel de información general de los choferes?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='opinion_servicio',
            field=models.CharField(choices=[('MB', 'Mejoró bastante'), ('MM', 'Mejoró medianamente'), ('MP', 'Mejoró poco'), ('NM', 'No mejoró'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿En este último tiempo, considera que el servicio brindado por la Empresa?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='opinion_trabajo_muni',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el trabajo que está realizando la Municipalidad para el control y mejoramiento del servicio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='sugerencia',
            field=models.CharField(blank='true', max_length=140, verbose_name='¿Tiene alguna sugerencia o comentario?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usa_medio_informacion',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza algún medio de información de transporte?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usa_recarga_sube',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza el servicio de recarga Sube con tarjeta de crédito?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usa_trasbordo',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza el servicio de trasbordo?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='trato_choferes',
            field=models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Trato y atención por parte de choferes'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(blank='true', choices=[('Z', 'Zona'), ('H', 'Hito'), ('P', 'Parada'), ('C', 'Calle'), ('B', 'Barrio')], max_length=1, verbose_name='Tipo de lugar'),
        ),
    ]
