# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 22:59
from __future__ import unicode_literals

import appencuesta.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appencuesta', '0009_auto_20161010_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cargaonline', models.BooleanField(default=True, verbose_name='Encuesta cargada en línea')),
                ('dia_realizada', models.DateField(default=datetime.date.today, verbose_name='fecha de realización')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('momento', models.CharField(blank='true', choices=[('AA', 'antes de ascender'), ('LD', 'luego de descender')], max_length=2, verbose_name='Momento de la encuesta')),
                ('sexo', models.CharField(blank='true', choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('rango_edad', models.CharField(blank='true', choices=[('JO', 'Jóven (18-25 años)'), ('A1', 'Adulto (25-40 años)'), ('A2', 'Adulto II (40-60 años)'), ('AM', 'Adulto mayor (más de 60 años)')], max_length=2, verbose_name='Rango de edad')),
                ('origen_parada', models.CharField(blank='true', max_length=10, verbose_name='Parada de destino (opcional)')),
                ('veces_semana', models.CharField(blank='true', choices=[('TODOS', 'Todos los días'), ('3OMAS', 'Tres o más'), ('MENOS3', 'Menos de tres')], max_length=6, verbose_name='Veces por semana en que realiza este viaje')),
                ('veces_dia', models.CharField(blank='true', choices=[('2OMAS', 'Dos o más'), ('MENOS2', 'Menos de dos')], max_length=6, verbose_name='Veces por día en que realiza este viaje')),
                ('otro_medio', models.CharField(blank='true', choices=[('NO', 'No'), ('OLINEA', 'Otra línea'), ('AUTO', 'Automóvil'), ('TAXREM', 'Taxi o Remis'), ('OTRO', 'Otro medio')], max_length=6, verbose_name='Para completar el viaje usa otro medio de transporte?')),
                ('estado_unidad', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Estado general de la unidad')),
                ('comodidad', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Comodidad con la que viaja')),
                ('higiene_unidad', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Higiene de la unidad')),
                ('trato_choferes', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='Trato y atención por parte de choferes')),
                ('conduccion_choferes', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el desempeño de los choferes en la conducción?')),
                ('info_choferes', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el nivel de información general de los choferes?')),
                ('usa_medio_informacion', models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza algún medio de información de transporte?')),
                ('usa_trasbordo', models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza el servicio de trasbordo?')),
                ('usa_recarga_sube', models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('NI', 'No me interesa'), ('NC', 'No lo conozco')], default='NO', max_length=2, verbose_name='¿Utiliza el servicio de recarga Sube con tarjeta de crédito?')),
                ('opinion_servicio', models.CharField(choices=[('MB', 'Mejoró bastante'), ('MM', 'Mejoró medianamente'), ('MP', 'Mejoró poco'), ('NM', 'No mejoró'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿En este último tiempo, considera que el servicio brindado por la Empresa?')),
                ('opinion_trabajo_muni', models.CharField(choices=[('MB', 'muy bueno'), ('BU', 'bueno'), ('RE', 'regular'), ('MA', 'malo'), ('NS', 'Ns/Nc')], default='NS', max_length=2, verbose_name='¿Cómo calificaría el trabajo que está realizando la Municipalidad para el control y mejoramiento del servicio?')),
                ('sugerencia', models.CharField(blank='true', max_length=140, verbose_name='¿Tiene alguna sugerencia o comentario?')),
                ('destino_lugar', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_destino_lugar', to='appencuesta.Lugar')),
                ('destino_motivo', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_destino_motivo', to='appencuesta.Motivo')),
                ('encuestador', models.ForeignKey(null='true', on_delete=appencuesta.models.Encuestador, to='appencuesta.Encuestador')),
                ('linea', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='appencuesta.Linea')),
                ('origen_lugar', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_origen_lugar', to='appencuesta.Lugar')),
                ('origen_motivo', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta_origen_motivo', to='appencuesta.Motivo')),
                ('parada_encuesta', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='appencuesta.Parada')),
            ],
        ),
    ]
